#!/usr/bin/env bash

# Function to minify HTML files
minify_html() {
    mv "$1" "$1.tmp" &&
        html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true >"$1" &&
        rm "$1.tmp"
}

# Function to minify CSS files
minify_css() {
    uglifycss "$1" >"$1.tmp" && mv "$1.tmp" "$1"
}

# Function to minify JS files
minify_js() {
    uglifyjs "$1" -o "$1" -c -m
}

# Backup dist directory
if [[ ! -d "dist_bak" ]]; then
    mkdir dist_bak
else
    sudo rm -r dist_bak
fi

cp -r ./dist dist_bak

# Minify HTML, CSS, and JS files recursively
find ./dist -type f -name "*.html" | while IFS= read -r file; do
    echo "$file"
    minify_html "$file"
done
# find ./dist -type f -name "*.css" -exec bash -c 'minify_css "$0"' {} \;
# find ./dist -type f -name "*.js" -exec bash -c 'minify_js "$0"' {} \;
