#!/usr/bin/env bash

# example use: stage newarticle.pug newintroimg.jpg
newpug=$1

mv "$newpug" ../src/blog/

full_filename=$(basename "${2}")
extension="${full_filename##*.}"
filename="${full_filename%.*}"

magick "${full_filename}" -resize 700 "${filename}_desktop.${extension}"
magick "${full_filename}" -resize 500 "${filename}_tablet.${extension}"
magick "${full_filename}" -resize 300 "${filename}_mobile.${extension}"
rm -i "${full_filename}"

mv "${filename}_"* ../dist/assets/images/intro_images/
